steps:
  - id: "Run Tests"
    name: python:3.12-slim
    entrypoint: bash
    args:
      - "-c"
      - "cd backend && pip install poetry && poetry install && poetry run pytest"

options:
  logging: CLOUD_LOGGING_ONLY