steps:
  - id: "Run Tests"
    name: python:3.12-slim
    entrypoint: bash
    args:
      - "-c"
      - "cd backend && pip install poetry && poetry install && poetry run pytest"

  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/budget-planner-backend:$COMMIT_SHA", "."]
  - id: "Push Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/budget-planner-backend:$COMMIT_SHA"]
  - id: "Deploy Cloud Run"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "budget-planner-backend",
        "--min-instances",
        "0",
        "--max-instances",
        "1",
        "--image",
        "gcr.io/$PROJECT_ID/budget-planner-backend:$COMMIT_SHA",
        "--region",
        "europe-west1",
        "--allow-unauthenticated",
        "--port",
        "8000",
      ]

images:
  - "gcr.io/$PROJECT_ID/budget-planner-backend:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
