version: '3.8'

services:
  backend:
    build: ./backend
    container_name: budget-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: budget-frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    container_name: budget-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budgetdb
    ports:
      - "5432:5432"

volumes:
  postgres_data:
