"""Add missing budget and user migrations

Revision ID: 6677da8baf0f
Revises: 8ace5a330a9e
Create Date: 2024-10-08 12:13:14.830323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6677da8baf0f'
down_revision: Union[str, None] = '8ace5a330a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
