"""Initial migration

Revision ID: 8ace5a330a9e
Revises: 
Create Date: 2024-10-08 11:13:17.393235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ace5a330a9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.drop_index('ix_budgets_name', table_name='budgets')
    op.drop_column('budgets', 'name')
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('incomes', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'created_at')
    op.drop_column('expenses', 'created_at')
    op.add_column('budgets', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_budgets_name', 'budgets', ['name'], unique=False)
    op.alter_column('budgets', 'total_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
